### ISSUE TITLE
Banners broke SWI..

### ISSUE THREAD

**Issue by TriptychPlaysMC** [ExtendedAlpha/SeparateWorldItems#1]
Okay so one major bug found for SWI for minecraft version 1.7.10 since there are no banners in 1.7x SWI is throwing an error saying can't find BANNER, i'm now looking into a fix one possible one is that we add a config option minecraft server 1.7x and below to disable banners but i'm not sure how well that will work.

**Comment by sgdc3** [comment]
Can you provide a download link for a stable 1.7.10 build? (http://www.spigotmc.org/resources/%E3%80%8Aseparate-world-items%E3%80%8Ba-mv-i-replacement.2568/update?update=23724)

**Comment by TriptychPlaysMC** [comment]
Yes this version on spigot will work and doesn't have any bugs that i know of.
http://www.spigotmc.org/resources/%E3%80%8Aseparate-world-items%E3%80%8Ba-mv-i-replacement.2568/download?version=18230

**Comment by sgdc3** [comment]
Thanks! ;)

**Comment by sgdc3** [comment]
[22:43:06 ERROR]: Could not pass event PlayerChangedWorldEvent to SWI v2.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.PlayerList.moveToWorld(PlayerList.java:622) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:526) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1046) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:883) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]
Caused by: java.lang.IllegalArgumentException: World 'Spawn' not found! Could not get group!
	at com.TriptychGames.SWI.Data.WorldManager.getGroupFromWorld(WorldManager.java:63) ~[?:?]
	at com.TriptychGames.SWI.Listeners.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:37) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[pspigot1710.jar:git-PaperSpigot-1.7.9-R0.2-271-g5978fa5]

**Comment by sgdc3** [comment]
my groups.yml file:
groups:
  Lobby:
    worlds:
    - Spawn
    default-gamemode: ADVENTURE
  Mondo:
    worlds:
    - Elementi
    default-gamemode: SURVIVAL

**Comment by TriptychPlaysMC** [comment]
You need to reset your groups.yml as the formatting changed a few versions back.

**Comment by sgdc3** [comment]
Ok, Thank you!  ;)

**Comment by hockeymikey** [comment]
Why not just check the version of the server with Bukkit.getBukkitVersion() or check if Material.BANNER exists?  And if it doesn't then set a Boolean that is checked whenever a banner related method is ran.

**Comment by TriptychPlaysMC** [comment]
I don't have time to do it right now. If you would like to you can, i'll have to give you edit permission though.

**Comment by hockeymikey** [comment]
Fair enough, I'll get working on a fix when I get some time.

**Comment by sgdc3** [comment]
He doesn't need write permission, he can just fork the project and create a pull request ;)

**Comment by sgdc3** [comment]
I should have fixed it! But needs testing ;) (I put the fix in my latest pull request)

**Comment by TriptychPlaysMC** [comment]
Issue now fixed in the latest dev build! http://ci.md-5.net/job/SeparateWorldItems/17/
Issue closed.
