### ISSUE TITLE
Another Error

### ISSUE THREAD

**Issue by Dennis000903** [ExtendedAlpha/SeparateWorldItems#29]
Spigot 1.8.6
with latest dev-build #34

I get this error when type /gamemode 0

Could not pass event PlayerGameModeChangeEvent to SeparateWorldItems v2.9.0-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:757) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:76) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.ExtendedAlpha.org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at com.ExtendedAlpha.org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:194) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:321) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:98) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:89) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.GameModeChangeEventListener.onPlayerGameModeChange(GameModeChangeEventListener.java:56) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 24 more

**Comment by Dennis000903** [comment]
Another error:

Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.9.0-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:158) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:68) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:39) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:72) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.ExtendedAlpha.org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at com.ExtendedAlpha.org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:194) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:321) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:98) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:89) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 29 more

**Comment by sgdc3** [comment]
It's always a problem with theplugin configuration, try deleting it and restart your server.

**Comment by Dennis000903** [comment]
Okay the Error is fixed with that, but theres still this error (plugin still working, but error )

Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.9.0-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:158) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:68) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:39) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:72) [EssentialsSpawn-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.ExtendedAlpha.org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at com.ExtendedAlpha.org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:194) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:321) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:98) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:89) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 29 more
[15:46:26 INFO]: DeWil issued server command: /gamemode 0
[15:46:26 ERROR]: Could not pass event PlayerGameModeChangeEvent to SeparateWorldItems v2.9.0-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:757) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:76) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.ExtendedAlpha.org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at com.ExtendedAlpha.org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:194) ~[?:?]
        at com.ExtendedAlpha.org.json.JSONObject.<init>(JSONObject.java:321) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:98) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:89) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.GameModeChangeEventListener.onPlayerGameModeChange(GameModeChangeEventListener.java:56) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 24 more

**Comment by sgdc3** [comment]
Still a configuration or data storage problem with JSON. Try deleting the entire folder of the plugin. (Obviously do a backup first)

**Comment by RustyDagger** [comment]
I am having the same Issue With could not pass event. 

I am using spigot 1.8.6
Multiverse Core To assign Gamemode's
And RoyalCommands is Incharge of /GM

http://pastebin.com/SgTcE0Aw

I have sufferd from inventory Loss And my creative inventory has Been moved to survival. This error only occurs when moving From or TO the Creative map ( all other maps are survival. )

Here is a copy of my config.
http://pastebin.com/uYUCNVw1
Here is a Copy of my Groups.Yml
http://pastebin.com/bxLrLiPK
My settings.json file.
http://pastebin.com/5RW6yiCq

Here is a screenshot of my Data Folder
http://prntscr.com/7d0cj9

It looks LIKE and It is Doing Per Gamemode inventories Ingame despite being told not to 

I cant find another UUID world Inventories Plugin  I need this working.

**Comment by sgdc3** [comment]
Try latest dev build and delete swi folder to reset everything. I think the problem is we renamed settings.json in the code.

**Comment by RustyDagger** [comment]
I have done what you listed above. However The plugin is still making per gamemode inventory saves despite it being set to false in both places in the config.yml.

I am still testing to see if i can create the error once more.

**Comment by sgdc3** [comment]
Thanks for your accurate explanation, we will get to work immediately to repair the problems ;)

**Comment by RustyDagger** [comment]
No problem Iv been hosting since before Bukkit off and on for years Iv made many issue and bug reports in my time and I know the more info the better only speeds fixing things up.

**Comment by TriptychPlaysMC** [comment]
Expect an update soon on spigot and the ci server fixing a few bugs this one is in the patch!

**Comment by TriptychPlaysMC** [comment]
Here you go! https://github.com/ExtendedAlpha/SeparateWorldItems/commit/93d8ce8b5817d1abc34c45e4d43ea8216558f3db

**Comment by Dennis000903** [comment]
Thanks it works

**Comment by TriptychPlaysMC** [comment]
Great to hear!
